In [2]:
from funkcije import *

## Učitavanje fičera
---

In [3]:
nemci = pd.read_csv("baza.csv")

In [4]:
nemci.head()

filename  kod_govornika kod_recenice kod_emocije naziv_emocije pol  \
0  03a01Fa.wav              3          a01           F         Sreća   M   
1  03a01Nc.wav              3          a01           N     Neutralno   M   
2  03a01Wa.wav              3          a01           W           Bes   M   
3  03a02Fc.wav              3          a02           F         Sreća   M   
4  03a02Nc.wav              3          a02           N     Neutralno   M   

   godiste  hurstovi    duzine  odnos_tišine_i_govora  najduža_priča  \
0       31  0.057822  0.027695               0.014496       0.016678   
1       31  0.051544  0.023508               0.012098       0.013819   
2       31  0.051150  0.027396               0.014676       0.016917   
3       31  0.048770  0.029270               0.015113       0.033119   
4       31  0.047226  0.021006               0.019172       0.027877   

   zcr_prosek   zcr_min   zcr_max   zcr_med  zcr_stdev  pitch_prosek  \
0    0.039627  0.000000  0.041737  0.035844   0.040875      0.034708   
1    0.027523  0.000000  0.034284  0.022568   0.032566      0.025073   
2    0.050864  0.100504  0.038425  0.063722   0.038340      0.039823   
3    0.042765  0.000000  0.046209  0.043809   0.040676      0.049342   
4    0.027608  0.000000  0.036437  0.023896   0.032225      0.023681   

   pitch_min  pitch_max  pitch_med  pitch_stdev  energija_prosek  \
0   0.031669   0.035054   0.034017     0.042673         0.017427   
1   0.027890   0.022468   0.027078     0.026987         0.042682   
2   0.047725   0.032331   0.041398     0.028820         0.041732   
3   0.045570   0.049004   0.046737     0.051125         0.039837   
4   0.028542   0.019003   0.025484     0.018476         0.057703   

   energija_min  energija_max  energija_stdev  eng_bez_tis  eng_bez_tis_avg  \
0      0.044139      0.032203        0.011907     0.025037         0.014647   
1      0.042051      0.043451        0.036026     0.042954         0.033954   
2      0.042269      0.045070        0.024851     0.044305         0.035076   
3      0.048514      0.055141        0.027702     0.043035         0.033512   
4      0.042335      0.052075        0.034992     0.058653         0.052259   

   eng_bez_tis_min  eng_bez_tis_max  eng_bez_tis_med  eng_bez_tis_stdev  \
0         0.002583         0.032203         0.007222           0.023040   
1         0.000579         0.043451         0.009349           0.040164   
2         0.000232         0.045070         0.017133           0.041947   
3         0.002959         0.055141         0.015307           0.040674   
4         0.007179         0.052075         0.018944           0.057258   

   energija_ukupna   mfcc_mean_1  mfcc_min_1  mfcc_max_1  mfcc_med_1  \
0         0.009818  5.815087e-09    -2.46963    1.765034    0.204909   
1         0.019309  5.815087e-09    -2.46963    1.765034    0.204909   
2         0.023258  5.815087e-09    -2.46963    1.765034    0.204909   
3         0.023722  5.815087e-09    -2.46963    1.765034    0.204909   
4         0.026543  5.815087e-09    -2.46963    1.765034    0.204909   

   mfcc_var_1   mfcc_mean_2  mfcc_min_2  mfcc_max_2  mfcc_med_2  mfcc_var_2  \
0         1.0  5.815087e-09    -2.46963    1.765034    0.204909         1.0   
1         1.0  5.815087e-09    -2.46963    1.765034    0.204909         1.0   
2         1.0  5.815087e-09    -2.46963    1.765034    0.204909         1.0   
3         1.0  5.815087e-09    -2.46963    1.765034    0.204909         1.0   
4         1.0  5.815087e-09    -2.46963    1.765034    0.204909         1.0   

    mfcc_mean_3  mfcc_min_3  mfcc_max_3  mfcc_med_3  mfcc_var_3   mfcc_mean_4  \
0  5.815087e-09    -2.46963    1.765034    0.204909         1.0  5.815087e-09   
1  5.815087e-09    -2.46963    1.765034    0.204909         1.0  5.815087e-09   
2  5.815087e-09    -2.46963    1.765034    0.204909         1.0  5.815087e-09   
3  5.815087e-09    -2.46963    1.765034    0.204909         1.0  5.815087e-09   
4  5.815087e-09    -2.46963    1.76

In [5]:
print(nemci.columns.values)

['filename' 'kod_govornika' 'kod_recenice' 'kod_emocije' 'naziv_emocije'
 'pol' 'godiste' 'hurstovi' 'duzine' 'odnos_tišine_i_govora'
 'najduža_priča' 'zcr_prosek' 'zcr_min' 'zcr_max' 'zcr_med' 'zcr_stdev'
 'pitch_prosek' 'pitch_min' 'pitch_max' 'pitch_med' 'pitch_stdev'
 'energija_prosek' 'energija_min' 'energija_max' 'energija_stdev'
 'eng_bez_tis' 'eng_bez_tis_avg' 'eng_bez_tis_min' 'eng_bez_tis_max'
 'eng_bez_tis_med' 'eng_bez_tis_stdev' 'energija_ukupna' 'mfcc_mean_1'
 'mfcc_min_1' 'mfcc_max_1' 'mfcc_med_1' 'mfcc_var_1' 'mfcc_mean_2'
 'mfcc_min_2' 'mfcc_max_2' 'mfcc_med_2' 'mfcc_var_2' 'mfcc_mean_3'
 'mfcc_min_3' 'mfcc_max_3' 'mfcc_med_3' 'mfcc_var_3' 'mfcc_mean_4'
 'mfcc_min_4' 'mfcc_max_4' 'mfcc_med_4' 'mfcc_var_4' 'mfcc_mean_5'
 'mfcc_min_5' 'mfcc_max_5' 'mfcc_med_5' 'mfcc_var_5' 'mfcc_mean_6'
 'mfcc_min_6' 'mfcc_max_6' 'mfcc_med_6' 'mfcc_var_6' 'mfcc_mean_7'
 'mfcc_min_7' 'mfcc_max_7' 'mfcc_med_7' 'mfcc_var_7' 'mfcc_mean_8'
 'mfcc_min_8' 'mfcc_max_8' 'mfcc_med_8' 'mfcc_var_8' 

### Dodavanje tuge i besa
---

In [6]:
nemci["bes"]        = (nemci["kod_emocije"] == "W") * 1.0
nemci["dosada"]     = (nemci["kod_emocije"] == "L") * 1.0
nemci["gadjenje"]   = (nemci["kod_emocije"] == "E") * 1.0
nemci["strah"]      = (nemci["kod_emocije"] == "A") * 1.0
nemci["sreca"]      = (nemci["kod_emocije"] == "F") * 1.0
nemci["tuga"]       = (nemci["kod_emocije"] == "T") * 1.0
nemci["neutralno"]  = (nemci["kod_emocije"] == "N") * 1.0
# nemci["nista"] = (nemci["tuga"] != 1) * 1.0
# nemci["nista"] = (nemci["bes"] != 1) * 1.0 * nemci["nista"]
# nemci

In [7]:
nemci.to_csv("baza_labelirana.csv", index=False)

In [8]:
proba = pd.read_csv("baza_labelirana.csv")
proba.head()

filename  kod_govornika kod_recenice kod_emocije naziv_emocije pol  \
0  03a01Fa.wav              3          a01           F         Sreća   M   
1  03a01Nc.wav              3          a01           N     Neutralno   M   
2  03a01Wa.wav              3          a01           W           Bes   M   
3  03a02Fc.wav              3          a02           F         Sreća   M   
4  03a02Nc.wav              3          a02           N     Neutralno   M   

   godiste  hurstovi    duzine  odnos_tišine_i_govora  najduža_priča  \
0       31  0.057822  0.027695               0.014496       0.016678   
1       31  0.051544  0.023508               0.012098       0.013819   
2       31  0.051150  0.027396               0.014676       0.016917   
3       31  0.048770  0.029270               0.015113       0.033119   
4       31  0.047226  0.021006               0.019172       0.027877   

   zcr_prosek   zcr_min   zcr_max   zcr_med  zcr_stdev  pitch_prosek  \
0    0.039627  0.000000  0.041737  0.035844   0.040875      0.034708   
1    0.027523  0.000000  0.034284  0.022568   0.032566      0.025073   
2    0.050864  0.100504  0.038425  0.063722   0.038340      0.039823   
3    0.042765  0.000000  0.046209  0.043809   0.040676      0.049342   
4    0.027608  0.000000  0.036437  0.023896   0.032225      0.023681   

   pitch_min  pitch_max  pitch_med  pitch_stdev  energija_prosek  \
0   0.031669   0.035054   0.034017     0.042673         0.017427   
1   0.027890   0.022468   0.027078     0.026987         0.042682   
2   0.047725   0.032331   0.041398     0.028820         0.041732   
3   0.045570   0.049004   0.046737     0.051125         0.039837   
4   0.028542   0.019003   0.025484     0.018476         0.057703   

   energija_min  energija_max  energija_stdev  eng_bez_tis  eng_bez_tis_avg  \
0      0.044139      0.032203        0.011907     0.025037         0.014647   
1      0.042051      0.043451        0.036026     0.042954         0.033954   
2      0.042269      0.045070        0.024851     0.044305         0.035076   
3      0.048514      0.055141        0.027702     0.043035         0.033512   
4      0.042335      0.052075        0.034992     0.058653         0.052259   

   eng_bez_tis_min  eng_bez_tis_max  eng_bez_tis_med  eng_bez_tis_stdev  \
0         0.002583         0.032203         0.007222           0.023040   
1         0.000579         0.043451         0.009349           0.040164   
2         0.000232         0.045070         0.017133           0.041947   
3         0.002959         0.055141         0.015307           0.040674   
4         0.007179         0.052075         0.018944           0.057258   

   energija_ukupna   mfcc_mean_1  mfcc_min_1  mfcc_max_1  mfcc_med_1  \
0         0.009818  5.815087e-09    -2.46963    1.765034    0.204909   
1         0.019309  5.815087e-09    -2.46963    1.765034    0.204909   
2         0.023258  5.815087e-09    -2.46963    1.765034    0.204909   
3         0.023722  5.815087e-09    -2.46963    1.765034    0.204909   
4         0.026543  5.815087e-09    -2.46963    1.765034    0.204909   

   mfcc_var_1   mfcc_mean_2  mfcc_min_2  mfcc_max_2  mfcc_med_2  mfcc_var_2  \
0         1.0  5.815087e-09    -2.46963    1.765034    0.204909         1.0   
1         1.0  5.815087e-09    -2.46963    1.765034    0.204909         1.0   
2         1.0  5.815087e-09    -2.46963    1.765034    0.204909         1.0   
3         1.0  5.815087e-09    -2.46963    1.765034    0.204909         1.0   
4         1.0  5.815087e-09    -2.46963    1.765034    0.204909         1.0   

    mfcc_mean_3  mfcc_min_3  mfcc_max_3  mfcc_med_3  mfcc_var_3   mfcc_mean_4  \
0  5.815087e-09    -2.46963    1.765034    0.204909         1.0  5.815087e-09   
1  5.815087e-09    -2.46963    1.765034    0.204909         1.0  5.815087e-09   
2  5.815087e-09    -2.46963    1.765034    0.204909         1.0  5.815087e-09   
3  5.815087e-09    -2.46963    1.765034    0.204909         1.0  5.815087e-09   
4  5.815087e-09    -2.46963    1.76

### matrica korelacije, fičeri prema emocijama

In [8]:
corr_matrix =  nemci.drop(["kod_emocije", "kod_recenice", "filename", "naziv_emocije", "pol", "godiste", "kod_govornika", "mfccovi", "mfccovi_x", "mfccovi_y"], axis=1).corr()

In [9]:
# corr_matrix
corr_matrix[["bes", "dosada",
"gadjenje",
"strah",
"sreca",   
"tuga",   
"neutralno"]].sort_values(by="gadjenje")
# corr_matrix.sort_values(by="bes")


bes    dosada  gadjenje     strah     sreca  \
bes                    1.000000 -0.235660 -0.171118 -0.214686 -0.218244   
dosada                -0.235660  1.000000 -0.129550 -0.162535 -0.165228   
neutralno             -0.232222 -0.175811 -0.127660 -0.160163 -0.162818   
sreca                 -0.218244 -0.165228 -0.119976 -0.150523  1.000000   
strah                 -0.214686 -0.162535 -0.118020  1.000000 -0.150523   
tuga                  -0.201993 -0.152925 -0.111043 -0.139315 -0.141624   
zcr_min                0.246537 -0.014495 -0.060930  0.035353 -0.075527   
eng_bez_tis_min       -0.165875  0.050783 -0.060361 -0.071033 -0.099548   
odnos_tišine_i_govora -0.201631  0.105562 -0.057698  0.069900 -0.115418   
hurstovi               0.030572 -0.000763 -0.042276 -0.005491  0.005184   
eng_bez_tis_stdev     -0.228723  0.207006 -0.041409 -0.030953 -0.100478   
eng_bez_tis           -0.200517  0.186639 -0.040355 -0.039818 -0.087753   
eng_bez_tis_avg       -0.332888  0.262268 -0.015822  0.008580 -0.152292   
zcr_med                0.644322 -0.278766 -0.015787  0.030401  0.129089   
energija_prosek       -0.321033  0.244027 -0.001461  0.004169 -0.142930   
pitch_med              0.436337 -0.314772 -0.000823  0.079651  0.331381   
pitch_stdev            0.329180 -0.083882  0.007228 -0.134583  0.332408   
energija_min          -0.067796  0.039497  0.009290  0.148305 -0.018557   
eng_bez_tis_med       -0.338572  0.287077  0.013529  0.077414 -0.154143   
energija_max          -0.152524  0.076303  0.016182 -0.021264 -0.051494   
eng_bez_tis_max       -0.152524  0.076303  0.016182 -0.021264 -0.051494   
pitch_prosek           0.428876 -0.289557  0.021314  0.072717  0.328837   
energija_stdev        -0.368610  0.236696  0.057412  0.081744 -0.149973   
pitch_max              0.361372 -0.174664  0.063009 -0.037566  0.313982   
zcr_prosek             0.496547 -0.294410  0.072487  0.152626  0.119251   
energija_ukupna       -0.316235  0.210196  0.072555 -0.108579 -0.178223   
pitch_min              0.093511 -0.192804  0.106569  0.208228  0.168693   
najduža_priča         -0.213701  0.188492  0.107627 -0.005506 -0.119061   
zcr_max                0.028780 -0.201152  0.118050  0.033638  0.230108   
zcr_stdev             -0.054540 -0.166589  0.167973  0.171435  0.092066   
duzine                -0.075397 -0.000260  0.171151 -0.204618 -0.089734   
gadjenje              -0.171118 -0.129550  1.000000 -0.118020 -0.119976   

                           tuga  neutralno  
bes                   -0.201993  -0.232222  
dosada                -0.152925  -0.175811  
neutralno             -0.150694   1.000000  
sreca                 -0.141624  -0.162818  
strah                 -0.139315  -0.160163  
tuga                   1.000000  -0.150694  
zcr_min               -0.110173  -0.094655  
eng_bez_tis_min        0.404172  -0.007035  
odnos_tišine_i_govora  0.235491   0.012620  
hurstovi               0.042916  -0.040979  
eng_bez_tis_stdev      0.150608   0.087327  
eng_bez_tis            0.148316   0.071517  
eng_bez_tis_avg        0.144822   0.153623  
zcr_med               -0.370672  -0.296349  
energija_prosek        0.136703   0.149025  
pitch_med             -0.330166  -0.298882  
pitch_stdev           -0.298854  -0.236842  
energija_min          -0.079171  -0.016870  
eng_bez_tis_med        0.024290   0.157670  
energija_max           0.162487   0.015773  
eng_bez_tis_max        0.162487   0.015773  
pitch_prosek          -0.343908  -0.311518  
energija_stdev         0.045669   0.182552  
pitch_max             -0.323124  -0.279946  
zcr_prosek            -0.342418  -0.304625  
energija_ukupna        0.400778   0.020973  
pitch_min             -0.197612  -0.181310  
najduža_priča          0.151912  -0.037199  
zcr_max               -0.127764  -0.061119  
zcr_stdev             -0.066236  -0.089253  
duzine                 0.448770  -0.170334  
gadjenje              -0.111043  -0.127660

In [9]:

## ovaj set fičera nam daje ~0.467 tačnost na testiranju, knn, k = 17, random_state = 12345, 80/20 split
X = nemci[["hurstovi", "duzine",
            "odnos_tišine_i_govora", "najduža_priča",	"zcr_prosek",
            "zcr_min",	"zcr_max",	"zcr_med",	"zcr_stdev",	"pitch_prosek",
            "pitch_min",	"pitch_max",	"pitch_med",	"pitch_stdev",	"energija_prosek",	"energija_min",
            "energija_max",	"energija_stdev", "eng_bez_tis",	"eng_bez_tis_avg",	"eng_bez_tis_min",
            "eng_bez_tis_max",	"eng_bez_tis_med",	"eng_bez_tis_stdev",	"energija_ukupna"]]




# X = nemci[["duzine",
#             "odnos_tišine_i_govora", "najduža_priča",	"zcr_prosek",
#             "zcr_min",	"zcr_max",	"zcr_med",	"zcr_stdev",	"pitch_prosek",
#             "pitch_min",	"pitch_max",	"pitch_med",	"pitch_stdev",	"energija_prosek",	"energija_min",
#             "energija_max",	"energija_stdev", "eng_bez_tis",	"eng_bez_tis_avg",	"eng_bez_tis_min",
#             "eng_bez_tis_max",	"eng_bez_tis_med",	"eng_bez_tis_stdev",	"energija_ukupna"]]

# X = nemci[["duzine"]]#, "zcr_med", "pitch_med", "energija_stdev", "energija_max", "najduža_priča"]]



# X = nemci[["zcr_med", "pitch_med", "energija_max", "najduža_priča", "hurstovi"]]


# X = nemci[["duzine",
#             "odnos_tišine_i_govora", "najduža_priča",	"zcr_prosek",	"zcr_max",	"zcr_med","pitch_prosek",
# 	"pitch_med",		"energija_prosek",	"energija_min",
#             "energija_max",	"eng_bez_tis_med",	"eng_bez_tis_stdev",	"energija_ukupna"]]


# y = nemci[["tuga", "bes", "nista"]]
y = nemci[["bes", "dosada",
"gadjenje",
"strah",
"sreca",   
"tuga",   
"neutralno"]]

X_train, X_test, y_train, y_test = train_test_split(
 X, y, test_size=0.2, random_state=12345
)

X = X.values
y = y.values

In [160]:
X = nemci[[ 'mfcc_mean_1',
 'mfcc_min_1', 'mfcc_max_1', 'mfcc_med_1', 'mfcc_var_1', 'mfcc_mean_2',
 'mfcc_min_2', 'mfcc_max_2', 'mfcc_med_2', 'mfcc_var_2', 'mfcc_mean_3',
 'mfcc_min_3', 'mfcc_max_3', 'mfcc_med_3', 'mfcc_var_3', 'mfcc_mean_4',
 'mfcc_min_4', 'mfcc_max_4', 'mfcc_med_4', 'mfcc_var_4', 'mfcc_mean_5',
 'mfcc_min_5', 'mfcc_max_5', 'mfcc_med_5', 'mfcc_var_5', 'mfcc_mean_6',
 'mfcc_min_6', 'mfcc_max_6', 'mfcc_med_6', 'mfcc_var_6', 'mfcc_mean_7',
 'mfcc_min_7', 'mfcc_max_7', 'mfcc_med_7', 'mfcc_var_7', 'mfcc_mean_8',
 'mfcc_min_8', 'mfcc_max_8', 'mfcc_med_8', 'mfcc_var_8', 'mfcc_mean_9',
 'mfcc_min_9', 'mfcc_max_9', 'mfcc_med_9', 'mfcc_var_9', 'mfcc_mean_10',
 'mfcc_min_10', 'mfcc_max_10', 'mfcc_med_10', 'mfcc_var_10', 'mfcc_mean_11',
 'mfcc_min_11', 'mfcc_max_11', 'mfcc_med_11', 'mfcc_var_11', 'mfcc_mean_12',
 'mfcc_min_12', 'mfcc_max_12', 'mfcc_med_12', 'mfcc_var_12', 'mfcc_mean_13',
 'mfcc_min_13', 'mfcc_max_13', 'mfcc_med_13', 'mfcc_var_13', 'mfcc_mean_14',
 'mfcc_min_14', 'mfcc_max_14', 'mfcc_med_14', 'mfcc_var_14', 'mfcc_mean_15',
 'mfcc_min_15', 'mfcc_max_15', 'mfcc_med_15', 'mfcc_var_15', 'mfcc_mean_16',
 'mfcc_min_16', 'mfcc_max_16', 'mfcc_med_16', 'mfcc_var_16', 'mfcc_mean_17',
 'mfcc_min_17', 'mfcc_max_17', 'mfcc_med_17', 'mfcc_var_17', 'mfcc_mean_18',
 'mfcc_min_18', 'mfcc_max_18', 'mfcc_med_18', 'mfcc_var_18', 'mfcc_mean_19',
 'mfcc_min_19', 'mfcc_max_19', 'mfcc_med_19', 'mfcc_var_19', 'mfcc_mean_20',
 'mfcc_min_20', 'mfcc_max_20', 'mfcc_med_20', 'mfcc_var_20']]

y = nemci[["bes", "dosada",
"gadjenje",
"strah",
"sreca",   
"tuga",   
"neutralno"]]

X_train, X_test, y_train, y_test = train_test_split(
 X, y, test_size=0.2, random_state=12345
)

X = X.values
y = y.values

In [128]:
X_train


hurstovi    duzine  odnos_tišine_i_govora  najduža_priča  zcr_prosek  \
403  0.039111  0.053672               0.020202       0.062902    0.030929   
17   0.043683  0.051031               0.018322       0.036574    0.035990   
461  0.034081  0.032291               0.063103       0.069216    0.022677   
486  0.041188  0.080078               0.013503       0.055158    0.054657   
164  0.041659  0.048641               0.050228       0.092804    0.030799   
..        ...       ...                    ...            ...         ...   
420  0.027646  0.026694               0.034509       0.055754    0.046396   
129  0.037662  0.033837               0.022137       0.033953    0.040838   
285  0.049121  0.021350               0.023490       0.021205    0.041399   
485  0.029738  0.042328               0.023987       0.042054    0.063878   
482  0.044061  0.046186               0.013538       0.053848    0.043765   

     zcr_min   zcr_max   zcr_med  zcr_stdev  pitch_prosek  pitch_min  \
403      0.0  0.048362  0.023896   0.046533      0.038094   0.042030   
17       0.0  0.038425  0.018586   0.043677      0.021013   0.029549   
461      0.0  0.044387  0.017258   0.033169      0.018506   0.021506   
486      0.0  0.045381  0.047792   0.050266      0.074652   0.062251   
164      0.0  0.037265  0.014603   0.035943      0.018229   0.022654   
..       ...       ...       ...        ...           ...        ...   
420      0.0  0.040743  0.045136   0.042930      0.031445   0.029209   
129      0.0  0.039418  0.035844   0.043291      0.048598   0.048841   
285      0.0  0.045050  0.026551   0.048952      0.039034   0.056755   
485      0.0  0.044553  0.069032   0.049123      0.063970   0.072338   
482      0.0  0.039087  0.038499   0.041462      0.039508   0.058418   

     pitch_max  pitch_med  pitch_stdev  energija_prosek  energija_min  \
403   0.031229   0.038850     0.020756         0.043776      0.042392   
17    0.016639   0.020819     0.009254         0.036608      0.042077   
461   0.016072   0.018229     0.013154         0.042246      0.042292   
486   0.251282   0.047417     0.358904         0.019557      0.043285   
164   0.013831   0.018335     0.005654         0.069239      0.043372   
..         ...        ...          ...              ...           ...   
420   0.025513   0.033240     0.025184         0.037141      0.043779   
129   0.046791   0.048807     0.037244         0.030099      0.043186   
285   0.031229   0.037527     0.017487         0.036429      0.042219   
485   0.052219   0.063477     0.035426         0.036420      0.042479   
482   0.029477   0.040220     0.009517         0.064792      0.042811   

     energija_max  energija_stdev  eng_bez_tis  eng_bez_tis_avg  \
403      0.040223        0.054003     0.035230         0.040201   
17       0.032597        0.035583     0.035309         0.032871   
461      0.033858        0.051926     0.036029         0.046275   
486      0.031920        0.019134     0.022790         0.015919   
164      0.047807        0.088301     0.056381         0.074066   
..            ...             ...          ...              ...   
420      0.032623        0.046647     0.029012         0.037561   
129      0.022627        0.029877     0.026840         0.027943   
285      0.050057        0.022347     0.056430         0.034794   
485      0.031786        0.044304     0.032655         0.034728   
482      0.045380        0.040696     0.061851         0.053798   

     eng_bez_tis_min  eng_bez_tis_max  eng_bez_tis_med  eng_bez_tis_stdev  \
403         0.001255         0.040223         0.037385           0.035598   
17          0.003959         0.032597         0.015859           0.034577   
461         0.000453         0.033858         0.061845           0.037579   
486         0.000212         0.031920         0.007752           0.021092   
164         0.017892         0.047807         0.102311           0.058736   
..               ...              ...              ...                .

In [10]:
knn_model = KNeighborsRegressor(n_neighbors=17)

In [11]:
knn_model.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=17)

In [255]:
clf = make_pipeline(preprocessing.StandardScaler(), sklearn.svm.SVC(gamma='auto'))
clf = sklearn.svm.SVC(kernel="linear")


In [ ]:

clf.fit(X_train, y_train)

In [12]:
train_preds = knn_model.predict(X_train)



mse = mean_squared_error(y_train, train_preds)
rmse = sqrt(mse)
rmse

0.2765715805656326

In [13]:
test_preds = knn_model.predict(X_test)
mse = mean_squared_error(y_test, test_preds)
rmse = sqrt(mse)
rmse

0.3077422326929821

In [14]:
print(test_preds)
# print(y_test)

[[0.64705882 0.         0.05882353 0.11764706 0.17647059 0.
  0.        ]
 [0.52941176 0.         0.         0.         0.47058824 0.
  0.        ]
 [0.64705882 0.11764706 0.         0.23529412 0.         0.
  0.        ]
 [0.35294118 0.         0.         0.11764706 0.52941176 0.
  0.        ]
 [0.         0.23529412 0.17647059 0.11764706 0.         0.23529412
  0.23529412]
 [0.05882353 0.11764706 0.05882353 0.11764706 0.58823529 0.
  0.05882353]
 [0.         0.35294118 0.05882353 0.11764706 0.         0.05882353
  0.41176471]
 [0.         0.41176471 0.05882353 0.         0.         0.05882353
  0.47058824]
 [0.         0.29411765 0.11764706 0.17647059 0.11764706 0.
  0.29411765]
 [0.05882353 0.11764706 0.17647059 0.41176471 0.05882353 0.
  0.17647059]
 [0.35294118 0.         0.         0.05882353 0.58823529 0.
  0.        ]
 [0.47058824 0.         0.         0.11764706 0.41176471 0.
  0.        ]
 [0.52941176 0.05882353 0.11764706 0.         0.29411765 0.
  0.        ]
 [0.         0

In [15]:
## bez ovoga mozemo se upucamo u nogu samo
test_p = test_preds.copy()
train_p = train_preds.copy()
for i in range(len(test_p)):
    # print(test_preds[i])
    # print(max(test_preds[i]))
    # print(test_preds[i].argmax())
    test_p[i,test_p[i].argmax()] = 1.0
    test_p[i] = test_p[i] == 1.0
# np.amax(test_preds,axis=1)

for i in range(len(train_p)):
    # print(train_preds[i])
    # print(max(test_preds[i]))
    # print(train_preds[i].argmax())
    train_p[i, train_p[i].argmax()] = 1.0
    train_p[i] = train_p[i] == 1.0

In [16]:
# test_p = (test_preds[:] == True) * 1.0
test_acc = accuracy_score(y_test, test_p)
print(test_acc)

0.4672897196261682


In [17]:
# train_p = (train_preds[:] == True) * 1.0
train_acc = accuracy_score(y_train, train_p)
print(train_acc)

0.602803738317757


In [18]:
# sum(y_test["bes"]  == 1)


In [19]:
test_conf_matrica = metrics.confusion_matrix(y_test.values.argmax(axis=1), test_p.argmax(axis=1))

In [20]:
train_conf_matrica = metrics.confusion_matrix(y_train.values.argmax(axis=1), train_p.argmax(axis=1))

### random forest 

In [270]:
from sklearn.ensemble import RandomForestClassifier

In [275]:
X = nemci[["hurstovi", "duzine",
            "odnos_tišine_i_govora", "najduža_priča",	"zcr_prosek",
            "zcr_min",	"zcr_max",	"zcr_med",	"zcr_stdev",	"pitch_prosek",
            "pitch_min",	"pitch_max",	"pitch_med",	"pitch_stdev",	"energija_prosek",	"energija_min",
            "energija_max",	"energija_stdev", "eng_bez_tis",	"eng_bez_tis_avg",	"eng_bez_tis_min",
            "eng_bez_tis_max",	"eng_bez_tis_med",	"eng_bez_tis_stdev",	"energija_ukupna"]]
y = nemci[["bes", "dosada",
"gadjenje",
"strah",
"sreca",   
"tuga",   
"neutralno"]]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=12345)
rf_model = RandomForestClassifier(n_estimators=50, max_features="auto", random_state=44)
rf_model.fit(X_train, y_train)

predictions = rf_model.predict(X_test)
print(predictions)

[[0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.

/home/zarko/.local/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:427: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


## rutina za čuvanje
---

In [26]:
### sta nam treba
### trening set, test set
### timestamp, accuracy na oba seta
### citav model jer smo tako u mogucnosti
### train i test predikcije
### matrice konfuzije kad vec cuvamo

### cuvanje modela
timestr = datetime.now().strftime("%Y_%m_%d-%H_%M_%S")

folder = 'rezultati/'
filename = folder + timestr + "_acc:" + str(round(test_acc*100)) 


# model_pickle = open(filename + ".model","wb")
# model_pickle.close()

sets_pickle = open(filename + ".pkl", "wb")

pickle.dump(knn_model, sets_pickle)
pickle.dump(X_train, sets_pickle)
pickle.dump(y_train, sets_pickle)
pickle.dump(X_test,  sets_pickle)
pickle.dump(y_test,  sets_pickle)
pickle.dump(train_p,  sets_pickle)
pickle.dump(test_p,  sets_pickle)
pickle.dump(train_preds,  sets_pickle)
pickle.dump(test_preds,  sets_pickle)
pickle.dump(train_acc,  sets_pickle)
pickle.dump(test_acc,  sets_pickle)

pickle.dump(train_conf_matrica,  sets_pickle)
pickle.dump(test_conf_matrica,  sets_pickle)


sets_pickle.close()



## rutina za učitavanje nazad
---

In [24]:
selektor = biraj_fajl()

FileChooser(path='/home/zarko/PFE/prepoznavanje-emocija/lk-s-2023-prepoznavanje-emocija', filename='', title='…

In [33]:

filename = selektor.selected


sets_pickle = open(filename, "rb")
knn_model = pickle.load(sets_pickle)
X_train = pickle.load(sets_pickle)
y_train = pickle.load(sets_pickle)
X_test  = pickle.load(sets_pickle)
y_test  = pickle.load(sets_pickle)
train_p = pickle.load(sets_pickle)
test_p  = pickle.load(sets_pickle)
train_preds = pickle.load(sets_pickle)
test_preds  = pickle.load(sets_pickle)
train_acc   = pickle.load(sets_pickle)
test_acc    = pickle.load(sets_pickle)

train_conf_matrica = pickle.load(sets_pickle)
test_conf_matrica  = pickle.load(sets_pickle)


sets_pickle.close()



In [34]:
print(train_acc)

0.602803738317757
