In [1]:
from funkcije import *

2023/07/28 12:18:19 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2023/07/28 12:18:20 INFO mlflow.tracking.fluent: Autologging successfully enabled for statsmodels.


## Učitavanje fičera
---

In [2]:
# nemci = pd.read_csv("baza.csv")

In [3]:
# nemci.head()

In [4]:
print(nemci.columns.values.tolist() ) 

NameError: name 'nemci' is not defined

In [9]:
nemci= pd.read_csv("baza_labelirana.csv")
nemci.head()

filename  kod_govornika kod_recenice kod_emocije naziv_emocije pol  \
0  03a01Fa.wav              3          a01           F         Sreća   M   
1  03a01Nc.wav              3          a01           N     Neutralno   M   
2  03a01Wa.wav              3          a01           W           Bes   M   
3  03a02Fc.wav              3          a02           F         Sreća   M   
4  03a02Nc.wav              3          a02           N     Neutralno   M   

   godiste  hurstovi    duzine  odnos_tišine_i_govora  najduža_priča  \
0       31  0.057822  0.027695               0.014496       0.016678   
1       31  0.051544  0.023508               0.012098       0.013819   
2       31  0.051150  0.027396               0.014676       0.016917   
3       31  0.048770  0.029270               0.015113       0.033119   
4       31  0.047226  0.021006               0.019172       0.027877   

   zcr_prosek   zcr_min   zcr_max   zcr_med  zcr_stdev  pitch_prosek  \
0    0.039627  0.000000  0.041737  0.035844   0.040875      0.034708   
1    0.027523  0.000000  0.034284  0.022568   0.032566      0.025073   
2    0.050864  0.100504  0.038425  0.063722   0.038340      0.039823   
3    0.042765  0.000000  0.046209  0.043809   0.040676      0.049342   
4    0.027608  0.000000  0.036437  0.023896   0.032225      0.023681   

   pitch_min  pitch_max  pitch_med  pitch_stdev  energija_prosek  \
0   0.031669   0.035054   0.034017     0.042673         0.017427   
1   0.027890   0.022468   0.027078     0.026987         0.042682   
2   0.047725   0.032331   0.041398     0.028820         0.041732   
3   0.045570   0.049004   0.046737     0.051125         0.039837   
4   0.028542   0.019003   0.025484     0.018476         0.057703   

   energija_min  energija_max  energija_stdev  eng_bez_tis  eng_bez_tis_avg  \
0      0.044139      0.032203        0.011907     0.025037         0.014647   
1      0.042051      0.043451        0.036026     0.042954         0.033954   
2      0.042269      0.045070        0.024851     0.044305         0.035076   
3      0.048514      0.055141        0.027702     0.043035         0.033512   
4      0.042335      0.052075        0.034992     0.058653         0.052259   

   eng_bez_tis_min  eng_bez_tis_max  eng_bez_tis_med  eng_bez_tis_stdev  \
0         0.002583         0.032203         0.007222           0.023040   
1         0.000579         0.043451         0.009349           0.040164   
2         0.000232         0.045070         0.017133           0.041947   
3         0.002959         0.055141         0.015307           0.040674   
4         0.007179         0.052075         0.018944           0.057258   

   energija_ukupna   mfcc_mean_1  mfcc_min_1  mfcc_max_1  mfcc_med_1  \
0         0.009818  5.815087e-09   -2.469630    1.765034    0.204909   
1         0.019309  3.405980e-09   -2.204192    1.615474    0.231646   
2         0.023258 -5.886879e-09   -2.352659    1.242284    0.222247   
3         0.023722  5.480887e-09   -2.321042    1.653798    0.217303   
4         0.026543  1.135327e-08   -2.284319    1.150461    0.322823   

   mfcc_var_1   mfcc_mean_2  mfcc_min_2  mfcc_max_2  mfcc_med_2  mfcc_var_2  \
0         1.0  7.268859e-09   -2.338358    1.534265    0.077846         1.0   
1         1.0 -6.811959e-09   -2.758083    1.166160    0.353376         1.0   
2         1.0  1.030204e-08   -2.662235    1.422763   -0.016376         1.0   
3         1.0  1.370222e-08   -2.352003    1.988904   -0.131137         1.0   
4         1.0 -2.270653e-08   -2.084083    1.516692    0.118976         1.0   

    mfcc_mean_3  mfcc_min_3  mfcc_max_3  mfcc_med_3  mfcc_var_3   mfcc_mean_4  \
0  1.017640e-08   -2.069342    1.799302   -0.073271         1.0  2.180658e-09   
1  5.108970e-09   -1.847638    2.170909   -0.148779         1.0  4.257475e-09   
2  2.943439e-09   -2.240010    1.927131    0.006794         1.0 -2.943439e-09   
3  6.851109e-09   -2.139066    2.502769   -0.108186         1.0 -1.370222e-08   
4 -3.784422e-09   -1.735897    2.26

### Dodavanje tuge i besa
---

In [19]:
nemci["bes"]        = (nemci["kod_emocije"] == "W") * 1.0
nemci["dosada"]     = (nemci["kod_emocije"] == "L") * 1.0
nemci["gadjenje"]   = (nemci["kod_emocije"] == "E") * 1.0
nemci["strah"]      = (nemci["kod_emocije"] == "A") * 1.0
nemci["sreca"]      = (nemci["kod_emocije"] == "F") * 1.0
nemci["tuga"]       = (nemci["kod_emocije"] == "T") * 1.0
nemci["neutralno"]  = (nemci["kod_emocije"] == "N") * 1.0
# nemci["nista"] = (nemci["tuga"] != 1) * 1.0
# nemci["nista"] = (nemci["bes"] != 1) * 1.0 * nemci["nista"]
# nemci




### dodavanje svega
# nemci["sve"] = (nemci["bes"] == 1.0) * 0
# nemci["sve"] = (nemci["dosada"] == 1.0) * 1 + nemci["sve"]
# nemci["sve"] = (nemci["gadjenje"] == 1.0) * 2 + nemci["sve"]
# nemci["sve"] = (nemci["strah"] == 1.0) * 3 + nemci["sve"]
# nemci["sve"] = (nemci["sreca"] == 1.0) * 4 + nemci["sve"]
# nemci["sve"] = (nemci["tuga"] == 1.0) * 5 + nemci["sve"]
# nemci["sve"] = (nemci["neutralno"] == 1.0) * 6 + nemci["sve"]


# nemci["sve"] = (nemci["bes"] == 1.0) * 0
# nemci["sve"] = (nemci["dosada"] == 1.0) * 1 + nemci["sve"]
# nemci["sve"] = (nemci["gadjenje"] == 1.0) * 2 + nemci["sve"]
# nemci["sve"] = (nemci["strah"] == 1.0) * 3 + nemci["sve"]
# nemci["sve"] = (nemci["sreca"] == 1.0) * 4 + nemci["sve"]
# nemci["sve"] = (nemci["tuga"] == 1.0) * 5 + nemci["sve"]
# nemci["sve"] = (nemci["neutralno"] == 1.0) * 6 + nemci["sve"]

# nemci = nemci.drop(["bes", "dosada", "tuga", "sreca", "neutralno", "gadjenje", "strah"],axis=1)

In [20]:
# nemci.to_csv("baza_labelirana.csv", index=False)

### matrica korelacije, fičeri prema emocijama

In [21]:
# corr_matrix =  nemci.drop(["kod_emocije", "kod_recenice", "filename", "naziv_emocije", "pol", "godiste", "kod_govornika", "mfccovi", "mfccovi_x", "mfccovi_y"], axis=1).corr()

In [22]:
# # corr_matrix
# corr_matrix[["bes", "dosada",
# "gadjenje",
# "strah",
# "sreca",   
# "tuga",   
# "neutralno"]].sort_values(by="gadjenje")
# # corr_matrix.sort_values(by="bes")


In [23]:
print(nemci.columns.values)

['filename' 'kod_govornika' 'kod_recenice' 'kod_emocije' 'naziv_emocije'
 'pol' 'godiste' 'hurstovi' 'duzine' 'odnos_tišine_i_govora'
 'najduža_priča' 'zcr_prosek' 'zcr_min' 'zcr_max' 'zcr_med' 'zcr_stdev'
 'pitch_prosek' 'pitch_min' 'pitch_max' 'pitch_med' 'pitch_stdev'
 'energija_prosek' 'energija_min' 'energija_max' 'energija_stdev'
 'eng_bez_tis' 'eng_bez_tis_avg' 'eng_bez_tis_min' 'eng_bez_tis_max'
 'eng_bez_tis_med' 'eng_bez_tis_stdev' 'energija_ukupna' 'mfcc_mean_1'
 'mfcc_min_1' 'mfcc_max_1' 'mfcc_med_1' 'mfcc_var_1' 'mfcc_mean_2'
 'mfcc_min_2' 'mfcc_max_2' 'mfcc_med_2' 'mfcc_var_2' 'mfcc_mean_3'
 'mfcc_min_3' 'mfcc_max_3' 'mfcc_med_3' 'mfcc_var_3' 'mfcc_mean_4'
 'mfcc_min_4' 'mfcc_max_4' 'mfcc_med_4' 'mfcc_var_4' 'mfcc_mean_5'
 'mfcc_min_5' 'mfcc_max_5' 'mfcc_med_5' 'mfcc_var_5' 'mfcc_mean_6'
 'mfcc_min_6' 'mfcc_max_6' 'mfcc_med_6' 'mfcc_var_6' 'mfcc_mean_7'
 'mfcc_min_7' 'mfcc_max_7' 'mfcc_med_7' 'mfcc_var_7' 'mfcc_mean_8'
 'mfcc_min_8' 'mfcc_max_8' 'mfcc_med_8' 'mfcc_var_8' 

In [43]:

## ovaj set fičera nam daje ~0.467 tačnost na testiranju, knn, k = 17, random_state = 12345, 80/20 split
# X = nemci[["hurstovi", "duzine",
#             "odnos_tišine_i_govora", "najduža_priča",	"zcr_prosek",
#             "zcr_min",	"zcr_max",	"zcr_med",	"zcr_stdev",	"pitch_prosek",
#             "pitch_min",	"pitch_max",	"pitch_med",	"pitch_stdev",	"energija_prosek",	"energija_min",
#             "energija_max",	"energija_stdev", "eng_bez_tis",	"eng_bez_tis_avg",	"eng_bez_tis_min",
#             "eng_bez_tis_max",	"eng_bez_tis_med",	"eng_bez_tis_stdev",	"energija_ukupna"]]




# X = nemci[["duzine",
#             "odnos_tišine_i_govora", "najduža_priča",	"zcr_prosek",
#             "zcr_min",	"zcr_max",	"zcr_med",	"zcr_stdev",	"pitch_prosek",
#             "pitch_min",	"pitch_max",	"pitch_med",	"pitch_stdev",	"energija_prosek",	"energija_min",
#             "energija_max",	"energija_stdev", "eng_bez_tis",	"eng_bez_tis_avg",	"eng_bez_tis_min",
#             "eng_bez_tis_max",	"eng_bez_tis_med",	"eng_bez_tis_stdev",	"energija_ukupna"]]

# X = nemci[["duzine"]]#, "zcr_med", "pitch_med", "energija_stdev", "energija_max", "najduža_priča"]]



# X = nemci[["zcr_med", "pitch_med", "energija_max", "najduža_priča", "hurstovi"]]


# X = nemci[["duzine",
#             "odnos_tišine_i_govora", "najduža_priča",	"zcr_prosek",	"zcr_max",	"zcr_med","pitch_prosek",
# 	"pitch_med",		"energija_prosek",	"energija_min",
#             "energija_max",	"eng_bez_tis_med",	"eng_bez_tis_stdev",	"energija_ukupna"]]

# X =  nemci[['hurstovi', 'duzine', 'odnos_tišine_i_govora',
#  'najduža_priča', 'zcr_prosek', 'zcr_min', 'zcr_max', 'zcr_med', 'zcr_stdev',
#  'pitch_prosek', 'pitch_min', 'pitch_max', 'pitch_med', 'pitch_stdev',
#  'energija_prosek', 'energija_min', 'energija_max', 'energija_stdev',
#  'eng_bez_tis', 'eng_bez_tis_avg', 'eng_bez_tis_min', 'eng_bez_tis_max',
#  'eng_bez_tis_med', 'eng_bez_tis_stdev', 'energija_ukupna']]


X = nemci[['hurstovi', 'duzine', 'odnos_tišine_i_govora',
 'najduža_priča', 'zcr_prosek', 'zcr_min', 'zcr_max', 'zcr_med', 'zcr_stdev',
 'pitch_prosek', 'pitch_min', 'pitch_max', 'pitch_med', 'pitch_stdev',
 'energija_prosek', 'energija_min', 'energija_max', 'energija_stdev',
 'eng_bez_tis', 'eng_bez_tis_avg', 'eng_bez_tis_min', 'eng_bez_tis_max',
 'eng_bez_tis_med', 'eng_bez_tis_stdev', 'energija_ukupna', 'mfcc_mean_1',
 'mfcc_min_1', 'mfcc_max_1', 'mfcc_med_1', 'mfcc_var_1', 'mfcc_mean_2',
 'mfcc_min_2', 'mfcc_max_2', 'mfcc_med_2', 'mfcc_var_2', 'mfcc_mean_3',
 'mfcc_min_3', 'mfcc_max_3', 'mfcc_med_3', 'mfcc_var_3', 'mfcc_mean_4',
 'mfcc_min_4', 'mfcc_max_4', 'mfcc_med_4', 'mfcc_var_4', 'mfcc_mean_5',
 'mfcc_min_5', 'mfcc_max_5', 'mfcc_med_5', 'mfcc_var_5', 'mfcc_mean_6',
 'mfcc_min_6', 'mfcc_max_6', 'mfcc_med_6', 'mfcc_var_6', 'mfcc_mean_7',
 'mfcc_min_7', 'mfcc_max_7', 'mfcc_med_7', 'mfcc_var_7', 'mfcc_mean_8',
 'mfcc_min_8', 'mfcc_max_8', 'mfcc_med_8', 'mfcc_var_8', 'mfcc_mean_9',
 'mfcc_min_9', 'mfcc_max_9', 'mfcc_med_9', 'mfcc_var_9', 'mfcc_mean_10',
 'mfcc_min_10', 'mfcc_max_10', 'mfcc_med_10', 'mfcc_var_10', 'mfcc_mean_11',
 'mfcc_min_11', 'mfcc_max_11', 'mfcc_med_11', 'mfcc_var_11', 'mfcc_mean_12',
 'mfcc_min_12', 'mfcc_max_12', 'mfcc_med_12', 'mfcc_var_12', 'mfcc_mean_13',
 'mfcc_min_13', 'mfcc_max_13', 'mfcc_med_13', 'mfcc_var_13', 'mfcc_mean_14',
 'mfcc_min_14', 'mfcc_max_14', 'mfcc_med_14', 'mfcc_var_14', 'mfcc_mean_15',
 'mfcc_min_15', 'mfcc_max_15', 'mfcc_med_15', 'mfcc_var_15', 'mfcc_mean_16',
 'mfcc_min_16', 'mfcc_max_16', 'mfcc_med_16', 'mfcc_var_16', 'mfcc_mean_17',
 'mfcc_min_17', 'mfcc_max_17', 'mfcc_med_17', 'mfcc_var_17', 'mfcc_mean_18',
 'mfcc_min_18', 'mfcc_max_18', 'mfcc_med_18', 'mfcc_var_18', 'mfcc_mean_19',
 'mfcc_min_19', 'mfcc_max_19', 'mfcc_med_19', 'mfcc_var_19', 'mfcc_mean_20',
 'mfcc_min_20', 'mfcc_max_20', 'mfcc_med_20', 'mfcc_var_20']]


 
# y = nemci[["tuga", "bes", "nista"]]
y = nemci[["bes", "dosada",
"gadjenje",
"strah",
"sreca",   
"tuga",   
"neutralno"]]

# y  = nemci[["sve"]]

# X_train, X_test, y_train, y_test = train_test_split(
#  X, y, test_size=0.3, 
# )

X = X.values
y = y.values ## ni ovde ga ne koristimo

In [44]:
# X = nemci[[ 'mfcc_mean_1',
#  'mfcc_min_1', 'mfcc_max_1', 'mfcc_med_1', 'mfcc_var_1', 'mfcc_mean_2',
#  'mfcc_min_2', 'mfcc_max_2', 'mfcc_med_2', 'mfcc_var_2', 'mfcc_mean_3',
#  'mfcc_min_3', 'mfcc_max_3', 'mfcc_med_3', 'mfcc_var_3', 'mfcc_mean_4',
#  'mfcc_min_4', 'mfcc_max_4', 'mfcc_med_4', 'mfcc_var_4', 'mfcc_mean_5',
#  'mfcc_min_5', 'mfcc_max_5', 'mfcc_med_5', 'mfcc_var_5', 'mfcc_mean_6',
#  'mfcc_min_6', 'mfcc_max_6', 'mfcc_med_6', 'mfcc_var_6', 'mfcc_mean_7',
#  'mfcc_min_7', 'mfcc_max_7', 'mfcc_med_7', 'mfcc_var_7', 'mfcc_mean_8',
#  'mfcc_min_8', 'mfcc_max_8', 'mfcc_med_8', 'mfcc_var_8', 'mfcc_mean_9',
#  'mfcc_min_9', 'mfcc_max_9', 'mfcc_med_9', 'mfcc_var_9', 'mfcc_mean_10',
#  'mfcc_min_10', 'mfcc_max_10', 'mfcc_med_10', 'mfcc_var_10', 'mfcc_mean_11',
#  'mfcc_min_11', 'mfcc_max_11', 'mfcc_med_11', 'mfcc_var_11', 'mfcc_mean_12',
#  'mfcc_min_12', 'mfcc_max_12', 'mfcc_med_12', 'mfcc_var_12', 'mfcc_mean_13',
#  'mfcc_min_13', 'mfcc_max_13', 'mfcc_med_13', 'mfcc_var_13', 'mfcc_mean_14',
#  'mfcc_min_14', 'mfcc_max_14', 'mfcc_med_14', 'mfcc_var_14', 'mfcc_mean_15',
#  'mfcc_min_15', 'mfcc_max_15', 'mfcc_med_15', 'mfcc_var_15', 'mfcc_mean_16',
#  'mfcc_min_16', 'mfcc_max_16', 'mfcc_med_16', 'mfcc_var_16', 'mfcc_mean_17',
#  'mfcc_min_17', 'mfcc_max_17', 'mfcc_med_17', 'mfcc_var_17', 'mfcc_mean_18',
#  'mfcc_min_18', 'mfcc_max_18', 'mfcc_med_18', 'mfcc_var_18', 'mfcc_mean_19',
#  'mfcc_min_19', 'mfcc_max_19', 'mfcc_med_19', 'mfcc_var_19', 'mfcc_mean_20',
#  'mfcc_min_20', 'mfcc_max_20', 'mfcc_med_20', 'mfcc_var_20']]

# y = nemci[["bes", "dosada",
# "gadjenje",
# "strah",
# "sreca",   
# "tuga",   
# "neutralno"]]

# X_train, X_test, y_train, y_test = train_test_split(
#  X, y, test_size=0.2, random_state=12345
# )

# X = X.values
# y = y.values ## ovo ne koristimo mada nek ostane

In [45]:
# X_train



In [46]:
# def get_metrics(y_true, y_pred):
#     """
#     Returns metrics for classification
#     """
#     return {
#         'accuracy': accuracy_score(y_true, y_pred),
#         'f1': f1_score(y_true, y_pred, average='macro'),
#         'precision': precision_score(y_true, y_pred, average='macro'),
#         'recall': recall_score(y_true, y_pred, average='macro'),
#         'confusion_matrix': ConfusionMatrix(actual_vector = y_true,predict_vector =  y_pred)
#     }

### KNN
---

In [42]:
acc =  []
f1 =   []
acct = []
prec = []
recall =   []
conf_mat = []

k = 20
for i in range(k):
    
    X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, 
    )
    
    clf = KNeighborsRegressor(n_neighbors=17)

    clf.fit(X_train, y_train)

    train_preds = clf.predict(X_train)
    test_preds = clf.predict(X_test)

    test_p = test_preds.copy()
    train_p = train_preds.copy()
    for i in range(len(test_p)):
        test_p[i,test_p[i].argmax()] = 1.0
        test_p[i] = test_p[i] == 1.0

    for i in range(len(train_p)):
        train_p[i, train_p[i].argmax()] = 1.0
        train_p[i] = train_p[i] == 1.0


    y_test = list(y_test)
    metrics = get_metrics(y_test, test_p)

    dataset = mlflow.data.from_numpy(X_test)
    mlflow.log_input(dataset, context="testing")

    mlflow.log_metrics(metrics)


    acc.append(metrics['accuracy'])
    f1.append(metrics['f1'])
    prec.append(metrics['precision'])
    recall.append(metrics['recall'])
    # conf_mat.append(metrics['confusion_matrix'])

    y_train = list(y_train)

    m1 = get_metrics(y_train, train_p)
    acct.append(m1['accuracy'])

mlflow.end_run()

acc_sr = sum(acc)/len(acc)
f1_sr =  sum(f1)/len(f1)
acc_std = max(max(acc)-acc_sr, acc_sr-min(acc))
f1_std = max(max(f1)-f1_sr, f1_sr-min(f1))

print(acc_sr, acc_std)
print(f1_sr, f1_std)
print("max acc:", max(acc))
print("min acc:", min(acc))
print("avg precision", sum(prec)/len(prec))
print("min precision:", min(prec) )
print("max precision:", max(prec) )
print("avg recall:", sum(recall)/len(recall))
print("min recall:",    min(recall) )
print("max recall:",    max(recall) )

print("\n Matrica konfuzije za max tacnost:", max(acc))

# metrics.confusion_matrix(y_test.values.argmax(axis=1), test_p.argmax(axis=1))
# min_conf = conf_mat[acc.index(max(acc))]
# disp = ConfusionMatrixDisplay(
#     clf,
#     conf_mat[0],
#     conf_mat[1],
#     display_labels=["bes", "dosada", "gadjenje", "strah", "sreca", "tuga", "neutralno"],
#     xticks_rotation="vertical",
#     cmap=plt.cm.Blues,
#     normalize=None,
# )
# sns.heatmap(min_conf)#, annot=True)
# print(min_conf)
# min_conf.plot()

2023/07/28 12:46:02 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '77d4152841b34fbb9ccbed8a84b022f6', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow


2023/07/28 12:46:02 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during sklearn autologging: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'https', 'http'}
2023/07/28 12:46:02 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during sklearn autologging: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'https', 'http'}
2023/07/28 12:46:02 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during sklearn autologging: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'https', 'http'}
2023/07/28 12:46:02 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during sklearn autologging: The configured tracking uri scheme: 'file' is invalid for use with the pr

0.37857142857142867 0.06801242236024857
0.34596887172918867 0.08966369843105704
max acc: 0.42857142857142855
min acc: 0.3105590062111801
avg precision 0.4492290796658012
min precision: 0.35713449314151885
max precision: 0.5252486114514416
avg recall: 0.34903996679435484
min recall: 0.2727240789900636
max recall: 0.39892928255138127

 Matrica konfuzije za max tacnost: 0.42857142857142855


In [18]:
# print(type(min_conf.plot))
# min_conf.plot()
# print(min_conf)
# min_conf.plot()
min_conf.print_matrix()

NameError: name 'min_conf' is not defined

In [ ]:
train_preds = clf.predict(X_train)



mse = mean_squared_error(y_train, train_preds)
rmse = sqrt(mse)
rmse

0.2824682578817792

In [100]:
test_preds = clf.predict(X_test)
mse = mean_squared_error(y_test, test_preds)
rmse = sqrt(mse)
rmse

0.2980529050582891

In [101]:
# print(np.round(test_preds))
# print(nemci)
# print(X_test)

In [102]:
# ## bez ovoga mozemo se upucamo u nogu samo
# test_p = test_preds.copy()
# train_p = train_preds.copy()
# for i in range(len(test_p)):
#     # print(test_preds[i])
#     # print(max(test_preds[i]))
#     # print(test_preds[i].argmax())
#     test_p[i,test_p[i].argmax()] = 1.0
#     test_p[i] = test_p[i] == 1.0
# # np.amax(test_preds,axis=1)

# for i in range(len(train_p)):
#     # print(train_preds[i])
#     # print(max(test_preds[i]))
#     # print(train_preds[i].argmax())
#     train_p[i, train_p[i].argmax()] = 1.0
#     train_p[i] = train_p[i] == 1.0

In [103]:
# test_p = test_preds
# train_p = train_preds

In [104]:
test_acc = accuracy_score(y_test, test_p)
print(test_acc)

0.515527950310559


In [105]:
train_acc = accuracy_score(y_train, train_p)
print(train_acc)

0.5828877005347594


In [41]:
test_conf_matrica = metrics.confusion_matrix(y_test.values.argmax(axis=1), test_p.argmax(axis=1))

In [42]:
train_conf_matrica = metrics.confusion_matrix(y_train.values.argmax(axis=1), train_p.argmax(axis=1))

In [43]:
print(train_conf_matrica)


[[78  0  2  3  5  0  0]
 [ 5 32  2  1  1  0 17]
 [ 9  3  9  6  1  0  6]
 [11  5  3 15  4  0  9]
 [23  2  2  3 20  0  0]
 [ 0 13  0  0  0 27  6]
 [ 1 13  0  3  0  1 33]]


### krosvalidacija

In [44]:
# print (np.mean(
# print(cross_val_score(clf, X, y, cv=20))


2023/07/28 08:15:19 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '33e69655096c43a7b421a2d4ffa3b61b', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow


2023/07/28 08:15:19 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during sklearn autologging: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'https', 'http'}
2023/07/28 08:15:19 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '3219c47e66e647209e3fcc10c16a6949', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow
2023/07/28 08:15:19 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during sklearn autologging: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'https', 'http'}
2023/07/28 08:15:19 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '9c092d4a139b44c0b0267c00c66d9136', which will track hyperparameters, performance metrics, model artifa

[ 0.14413493  0.06774612  0.23300359  0.29183923  0.15635749  0.32561764
 -0.20333823  0.1632533   0.2201351   0.22893304  0.24817975  0.19578802
  0.23812108  0.19685235  0.33508514  0.16380751  0.26911887  0.12032135
  0.24488259  0.07370193]


## rutina za čuvanje
---

In [32]:
### sta nam treba
### trening set, test set
### timestamp, accuracy na oba seta
### citav model jer smo tako u mogucnosti
### train i test predikcije
### matrice konfuzije kad vec cuvamo

### cuvanje modela
timestr = datetime.now().strftime("%Y_%m_%d-%H_%M_%S")

folder = 'rezultati/'
filename = folder + timestr + "_acc:" + str(round(test_acc*100)) 


# model_pickle = open(filename + ".model","wb")
# model_pickle.close()

sets_pickle = open(filename + ".pkl", "wb")

pickle.dump(clf, sets_pickle)
pickle.dump(X_train, sets_pickle)
pickle.dump(y_train, sets_pickle)
pickle.dump(X_test,  sets_pickle)
pickle.dump(y_test,  sets_pickle)
pickle.dump(train_p,  sets_pickle)
pickle.dump(test_p,  sets_pickle)
pickle.dump(train_preds,  sets_pickle)
pickle.dump(test_preds,  sets_pickle)
pickle.dump(train_acc,  sets_pickle)
pickle.dump(test_acc,  sets_pickle)

pickle.dump(train_conf_matrica,  sets_pickle)
pickle.dump(test_conf_matrica,  sets_pickle)


sets_pickle.close()



## rutina za učitavanje nazad
---

In [ ]:
selektor = biraj_fajl()

In [ ]:

filename = selektor.selected


sets_pickle = open(filename, "rb")
knn_model = pickle.load(sets_pickle)
X_train = pickle.load(sets_pickle)
y_train = pickle.load(sets_pickle)
X_test  = pickle.load(sets_pickle)
y_test  = pickle.load(sets_pickle)
train_p = pickle.load(sets_pickle)
test_p  = pickle.load(sets_pickle)
train_preds = pickle.load(sets_pickle)
test_preds  = pickle.load(sets_pickle)
train_acc   = pickle.load(sets_pickle)
test_acc    = pickle.load(sets_pickle)

train_conf_matrica = pickle.load(sets_pickle)
test_conf_matrica  = pickle.load(sets_pickle)


sets_pickle.close()

